spring:
  application:
    name: recruit_jogbo
  messages:
    basename: i18n/messages
    encoding: UTF-8
  rabbitmq:
    host: HOST_IP
    port: 5672
    username: USERNAME
    password: PASSWORD
    virtual-host: VIRTUAL_HOST
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate.type: trace
jwt:
  token:
    header: api_key
    issuer: recruit_jogbo
    clientSecret: CLIENT_SECRET
    expirySeconds: 3600