spring:
  application:
    name: recruit_jogbo
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: HOST_IP
    port: 5672
    username: USERNAME
    password: PASSWORD
    virtual-host: VIRTUAL_HOST
logging:
  level:
    org.hibernate.type: trace
server:
  port: 8082