version: "3"
services:
  rabbit-mq:
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672
      - 8090:15672
    env_file:
      - rabbit-properties.env
  app:
    image: recruit-jogbo
    env_file:
      - recruit-jogbo-rabbit-properties.env
      - recruit-jogbo-properties.env
    ports:
      - 8080:8080
  mail-server:
    image: recruit-jogbo-mail
    ports:
      - 8081:8081
    env_file:
      - recruit-jogbo-rabbit-properties.env