version: "3"
services:
  rabbit-mq:
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672
      - 8090:15672
    env_file:
      - ../env/rabbit-properties.env
  app:
    image: hellozin/recruit-jogbo-api
    env_file:
      - ../env/recruit-jogbo-rabbit-properties.env
      - ../env/recruit-jogbo-properties.env
    ports:
      - 8080:8080
    depends_on:
      - rabbit-mq
  mail-server:
    image: hellozin/recruit-jogbo-mail
    ports:
      - 8081:8081
    env_file:
      - ../env/recruit-jogbo-rabbit-properties.env
      - ../env/recruit-jogbo-mail-properties.env
    depends_on:
      - rabbit-mq
  frontend:
    image: hellozin/recruit-jogbo-frontend
    ports:
      - 8082:80