spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate.type: trace
jwt:
  token:
    header: api_key
    issuer: recruit_jogbo
    clientSecret: CLIENT_SECRET # Secret for JWT
    expirySeconds: 0